### ISSUE TITLE
Can this be used with Drupal CMS ?

### ISSUE THREAD

**Issue by IbnSaeed** [AustP/Stylus.php#11]
Hello

Can this be used with Drupal CMS in designing a theme?

**Comment by LinusU** [comment]
I think that this question is better asked to the Drupal CMS.

If you are creating a theme I would recommend you to use the real stylus to compile the assets before releasing (or putting into production) your theme. This could be done with the standard stylus tool `stylus < my-file.styl > main.css` or by using a build tool such as [`gulp`](http://gulpjs.com/).

**Comment by IbnSaeed** [comment]
Thanks LinusU

**Comment by LinusU** [comment]
No problem, good luck with your theme!
